---
title: Olivier Theron
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    cover_img: img/logo-OT.png
    layout: post
  uploads:
    title: Uploads
    output: true
exclude:
- "/vendor/"
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- "*.gemspec"
keep_files:
- CNAME
- ".git"
- ".gitignore"
subtitle: A free HTML5 agency template
url: http://louptheron.github.io/
cover: "/assets/cover.png"
logo: "/assets/logo.png"
markdown: kramdown
plugins:
- jekyll-paginate
descriptions:
- cat: jekyll
  desc: Posts describing Jekyll setup techniques.
- cat: dummy
  desc: Just some placeholder posts, lorem ipsum and the rest.
paginate: 4
paginate_path: blog/:num/
