---
title: Airspace
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    cover_img: img/logo-OT.png
    layout: post
  uploads:
    title: Uploads
    output: true
exclude:
- "/vendor/"
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- "*.gemspec"
keep_files:
- CNAME
- ".git"
- ".gitignore"
subtitle: A free HTML5 agency template
url: http://louptheron.github.io/
baseurl: "/ot-jekyll"
cover: "/assets/cover.png"
logo: "/assets/logo.png"
markdown: kramdown
plugins:
- jekyll-paginate-v2
descriptions:
- cat: jekyll
  desc: Posts describing Jekyll setup techniques.
- cat: dummy
  desc: Just some placeholder posts, lorem ipsum and the rest.
pagination:
  enabled: true
  debug: false
  collection: posts
  per_page: 4
  permalink: "/:num/"
  title: ":title - blog :num"
  limit: 0
  sort_field: date
  sort_reverse: true
  category: posts
  tag: 
  locale: 
  trail:
    before: 2
    after: 2
  extension: html
